<?php
// $Id: wsuser.install 407 2007-10-26 18:51:13Z rfay $
function wsuser_update_1() {
	watchdog('update',"wsuser: updating tables wsuser to utf8");
    return _system_update_utf8(array('wsuser'));
}

function wsuser_update_2() {
	$sql = "ALTER TABLE wsuser ADD INDEX notcurrentlyavailable(notcurrentlyavailable)";
	$ret[] = update_sql($sql);
	return $ret;
}

function wsuser_update_3() {
	$sql = "delete from wsuser using wsuser left join users u on u.uid=wsuser.uid
where u.uid is null";
	$return[] = update_sql($sql);
	$num_rows_affected = db_affected_rows();
	watchdog('update',"wsuser_update_3: Deleted $num_rows_affected orphaned wsuser elements from wsuser table");
	return $return;
	
}
function wsuser_update_4() {
	global $user;
	watchdog('update',"UID for update is $user->uid");
}

function wsuser_update_5() {
	// Invalidate any existing sessions. Shd be done elsewhere but we'll do it here
	$sql = "delete from sessions where uid>1";
	$return[] = update_sql($sql);  
	$num_rows_affected=db_affected_rows();
	$return[0]['query'] .= " ($num_rows_affected sessions deleted)";
	return $return;
}

function wsuser_update_6() {
	// Add new columns for tracking member availability
	$sql = "alter table {wsuser} add isstale integer default '0'";
	$returns[] = update_sql($sql);
	$sql = "alter table {wsuser} add isstale_date integer default '0'";
	$returns[] = update_sql($sql);
	$sql = "alter table {wsuser} add column isstale_reason varchar(40)";
	$returns[] = update_sql($sql);
	
	$sql = "alter table {wsuser} add isunreachable integer default '0'";
	$returns[] = update_sql($sql);
	$sql = "alter table {wsuser} add unreachable_date integer default '0'";
	$returns[] = update_sql($sql);
	$sql = "alter table {wsuser} add column unreachable_reason varchar(40)";
	$returns[] = update_sql($sql);

	$sql = "alter table {wsuser} add column notcurrentlyavailable_reason varchar(120) after notcurrentlyavailable";
	$returns[] = update_sql($sql);
	
	// no longer used
	$sql = "alter table {wsuser} drop availability";
	$returns[] = update_sql($sql);
	$returns[] = update_sql("alter table {wsuser} drop nearest_large_city");
	
	return $returns;
}