<?php

// $Id: user_location.install 386 2007-10-20 21:36:10Z rfay $


// Consider adding the alter of tablename location to user_location here
// Consider changing wsuser name here to wsuser_full_name
// Load user_location_countries/provinces

// Load geonames* ?
function user_location_install() {
	switch ($GLOBALS['db_type']) {
		case 'mysql':
		case 'mysqli':
//			if (!module_exists('location') && db_table_exists('location'))  {
//				rename_location_table();
//				watchdog('install', "user_location install: Changed name of table to user_location");				//_system_update_utf8(array('user_location'));
//			}
			break;
			
			
		default:
			drupal_set_message("User_location: Unsupported database");
			break;
	}
}

function rename_location_table() {
	$sql = "rename table location to user_location";
	$result = db_query($sql);
    return array('success' => $result !== FALSE, 'query' => check_plain($sql));

}


function user_location_update_3() {
	if (!module_exists('location') && db_table_exists('location'))  {
		$ret[] = rename_location_table();
		// watchdog('install', "user_location install: Changed name of table to user_location");
	}

	watchdog('update',"user_location: updating tables user_location and wsuser");
    $ret[] = _system_update_utf8(array('user_location'));
    return $ret;
}  


function user_location_update_4() {
	$sql = "ALTER TABLE user_location DROP COLUMN name";
	$ret[] = update_sql($sql);
	return $ret;
}

function user_location_update_5() {
	$sql = "ALTER TABLE user_location DROP PRIMARY KEY,
 ADD PRIMARY KEY(oid),
 ADD INDEX country(country),
 ADD INDEX province(province),
 ADD INDEX latlon(latitude, longitude),
 ADD INDEX source(source)";
	$ret[]=update_sql($sql);
	return $ret;
}

function user_location_update_6() {
	$sql = "delete from user_location using user_location left join users u on u.uid=user_location.oid
where u.uid is null";
	$return[] = update_sql($sql);
	$num_rows_affected = db_affected_rows();
	watchdog('update',"user_location update 6: Deleted $num_rows_affected orphaned user_location elements from user_location table");
	$return[0]['query'] .= " (deleted $num_rows_affected rows in user_location table)";
	return $return;
	
}

function user_location_update_7() {
	// Put the set map location tab before the notify tab
	$sql = "update {system} set weight = 20 where name='user_location'";
	$return[] = update_sql($sql);
	return $return;
}

function user_location_update_8() {
	// Make sure province and country for all members is lowercase
	$sql = "update {user_location} set country=lcase(country), province=lcase(province)";
	$return[] = update_sql($sql);
	return $return;
}

