<?php
 /**
  * Implementation of hook_install()
  */
function manage_blocked_install() {
  switch ($GLOBALS['db_type']) {
    case 'mysql':
    case 'mysqli':
      db_query("CREATE TABLE {manage_blocked} (
                  uid INT (10) NOT NULL ,
                  last_reminder INTEGER NULL ,
                  msg_cnt INT (10) NULL ,
                  PRIMARY KEY (uid) ,
                  INDEX (last_reminder),
                  INDEX (msg_cnt)
                )");

    break; 
  }
}

/**
 * Implementation of hook_uninstall()
 */
function manage_blocked_uninstall(){
  db_query("DROP TABLE {manage_blocked}");
  variable_del('manage_blocked_initial');
  variable_del('manage_blocked_frequency');
  variable_del('manage_blocked_total');
  variable_del('manage_blocked_subject');
  variable_del('manage_blocked_msg'); 
}

